### ISSUE TITLE
Question about local Image optimization loader

### ISSUE THREAD

**Issue by pszafer** [milliHQ/pixel#1]
Hi, very interesting project.
I see that you use minio as local storage.
Do you maybe have example with following:
```
Client --> Cloudfront CDN --> Local NodeJS API with @dealmore/tf-next-image-optimization on Docker or PM2 etc. --> Minio S3
```

**Comment by ofhouse** [comment]
A bit late, but we finally published an package that allows the usage of the image optimization API with express: [`@millihq/pixel-express`](https://www.npmjs.com/package/@millihq/pixel-express)
